#!/bin/bash

# This file wraps the bootstrap processes for the SITCH service.


# Set env vars
source .env

# First we try to determine the distribution...
if [ -f /etc/lsb-release ]; then
  export `cat /etc/lsb-release | grep DISTRIB_ID | head -1`
elif [ -f /etc/redhat-release ]; then
  export DISTRIB_ID=`cat /etc/redhat-release | head -1 | awk '{print $1}'`
fi

# If we can't determine the distribution, we exit.
if [ -z ${DISTRIB_ID} ]; then
  echo "Unable to determine distribution! Exiting!!"
  exit 1
fi

# We look to see if the distribution is supported.  If not, we exit.
case "${DISTRIB_ID}" in
    Ubuntu)
        echo "Ubuntu found!"
        /bin/bash ./ubuntu/install-docker.sh
        ;;
    Debian)
        echo "Debian found!"
        /bin/bash ./debian/install-docker.sh
        ;;
    *)
        echo "Unsupported OS: ${DISTRIB_ID}! EXITING"
        exit 1
esac

# Get letsencrypt certs...
/bin/bash ./general/lets-encrypt.sh

# Requires copying Vault keys and root token, then pasting 3 keys back
/bin/bash ./general/vault.sh

# Vault root token will needed for this script and for docker-compose
echo Paste the root token generated by Vault
read VAULT_TOKEN
export VAULT_TOKEN
/bin/bash ./general/logstash.sh

/usr/local/bin/docker-compose -f ../docker-compose.yml up -d
