echo Generating logstash certificates...

echo Paste the root token generated by Vault
read VAULT_TOKEN

docker run -it \
  -e VAULT_URL=$VAULT_URL \
  -e VAULT_TOKEN=$VAULT_TOKEN \
  -e LS_CLIENTNAME=$LS_CLIENTNAME \
  -e LS_SERVERNAME=$LS_SERVERNAME \
  docker.io/sitch/self_signed_seeder
